blank_issues_enabled: false
contact_links:
  - name: ğŸŒ App Rejection Fixes Official Website
    url: https://wangchujiang.com/app-rejection-fixes/
    about: This repository documents the various reasons why apps were rejected during the App Store review process and provides solutions to resolve these issues. 